version: '3.4'

services:
    db:
        image: ape
        restart: always
        build:
            context: .
            dockerfile: APE.Api/APE.Api/Db/docker/Dockerfile
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: apeapi
        ports:
            - "5432:5432"
        networks:
            - home-network

    apeapi:
        image: apeapi
        build:
            context: .
            dockerfile: APE.Api/APE.Api/Dockerfile
        environment:
            TZ: America/Sao_Paulo
            ASPNETCORE_ENVIRONMENT: Production
        ports:
            - "5000:80"
        depends_on:
            - db
        networks:
            - home-network

    frontend:
        image: nginx
        volumes: 
            - ./frotend:/usr/share/nginx/html/
        ports:
            - "80:80"
        depends_on:
            - apeapi
        networks:
            - home-network


networks:
    home-network:
        driver: bridge
